# Generated by Django 6.0.5 on 2026-06-01 14:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100, unique=True, verbose_name='Intitulé du poste')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('ADMIN', 'Administrateur'), ('RH', 'Gestionnaire RH'), ('MANAGER', 'Manager / Chef'), ('AGENT', 'Agent Standard')], max_length=20, unique=True, verbose_name='Code du rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description des droits')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
            },
        ),
        migrations.CreateModel(
            name='Structure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=150, unique=True, verbose_name='Nom de la direction/service')),
                ('code', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('matricule', models.CharField(max_length=30, unique=True, verbose_name='Identifiant / Matricule')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email Professionnelle')),
                ('is_active', models.BooleanField(default=True, verbose_name='Compte actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Accès Django Admin')),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='agents_utilisateur_groups_set', related_query_name='agents_utilisateur', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='agents_utilisateur_permissions_set', related_query_name='agents_utilisateur', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='utilisateurs', to='agents.role', verbose_name="Rôle d'accès")),
            ],
            options={
                'verbose_name': 'Utilisateur',
                'verbose_name_plural': 'Utilisateurs',
            },
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name="Matricule de l'État")),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('date_naissance', models.DateField()),
                ('date_recrutement', models.DateField()),
                ('statut', models.CharField(choices=[('ACTIF', 'En Activité'), ('DETACHE', 'En Détachement'), ('RETRAITE', 'À la Retraite')], default='ACTIF', max_length=15)),
                ('corps', models.CharField(help_text='Ex: Administrateur Civil, Ingénieur', max_length=100)),
                ('grade', models.CharField(max_length=50)),
                ('echelon', models.IntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('compte_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_profil', to=settings.AUTH_USER_MODEL, verbose_name="Compte d'authentification")),
                ('structure', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='agents.structure')),
            ],
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé Annuel'), ('MALADIE', 'Congé Maladie'), ('MATERNITE', 'Maternité / Paternité'), ('SANS_SOLDE', 'Sans Solde')], default='ANNUEL', max_length=20, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='ATTENTE', max_length=15, verbose_name='Statut')),
                ('duree_jours_stockee', models.IntegerField(default=0, editable=False, verbose_name='Nombre de jours')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='agents.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateField(verbose_name="Date de l'entretien")),
                ('annee_eval_nom', models.IntegerField(default=2026, verbose_name='Année évaluée')),
                ('competence_technique', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Compétences Techniques (/20)')),
                ('sens_du_service', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Sens du Service (/20)')),
                ('assiduite', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Assiduité (/20)')),
                ('objectif_atteint', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Objectifs Atteints (/20)')),
                ('commentaire_general', models.TextField(blank=True, verbose_name='Commentaires')),
                ('souhaits_evolution', models.TextField(blank=True, verbose_name="Souhaits d'évolution")),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_generales', to='agents.agent', verbose_name='Agent évalué')),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_effectuees', to='agents.agent', verbose_name='Supérieur Hiérarchique')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='GrilleIndiciaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='Grade')),
                ('echelon', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Échelon')),
                ('indice_brut', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Indice Brut')),
                ('duree_minimum_mois', models.IntegerField(default=24, verbose_name='Durée minimale (mois) pour avancement')),
            ],
            options={
                'verbose_name': 'Grille Indiciaire',
                'verbose_name_plural': 'Grilles Indiciaires',
                'ordering': ['grade', 'echelon'],
                'unique_together': {('grade', 'echelon')},
            },
        ),
        migrations.CreateModel(
            name='EvolutionCarriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_promotion', models.DateField(auto_now_add=True, verbose_name="Date de l'évolution")),
                ('motif', models.CharField(default="Avancement à l'ancienneté", max_length=255, verbose_name='Motif')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_carriere', to='agents.agent', verbose_name='Agent')),
                ('ancien_grade_echelon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_evolutions', to='agents.grilleindiciaire')),
                ('nouveau_grade_echelon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nouvelles_evolutions', to='agents.grilleindiciaire', verbose_name='Nouveau Grade/Échelon')),
            ],
            options={
                'verbose_name': 'Évolution de Carrière',
                'verbose_name_plural': 'Évolutions de Carrière',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du service')),
                ('directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirige_service', to='agents.agent', verbose_name='Chef de service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='EvaluationAnnuelle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annee', models.IntegerField()),
                ('note', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(20.0)])),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_annuelles', to='agents.agent')),
            ],
            options={
                'unique_together': {('agent', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('salaire_base_historique', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Salaire de base (Figé)')),
                ('net_a_payer_stocke', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Net à Payer (Stocké)')),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primes complémentaires')),
                ('indemnite_residence', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Indemnité de résidence')),
                ('SFT', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Supplément Familial de Traitement (SFT)')),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres retenues / Avances')),
                ('retenues_retraite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retenue Retraite')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_paie', to='agents.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Bulletin de Paie',
                'verbose_name_plural': 'Bulletins de Paie',
                'unique_together': {('agent', 'mois', 'annee')},
            },
        ),
    ]
