# Generated by Django 6.0.5 on 2026-06-01 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='utilisateur',
            name='matricule',
            field=models.CharField(max_length=30, unique=True, verbose_name='Identifiant'),
        ),
    ]
