# Generated by Django 6.0.5 on 2026-05-26 15:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True, verbose_name='N° Matricule')),
                ('nom', models.CharField(max_length=100, verbose_name='Nom')),
                ('prenom', models.CharField(max_length=100, verbose_name='Prénom(s)')),
                ('genre', models.CharField(choices=[('M', 'Masculin'), ('F', 'Féminin')], default='M', max_length=1, verbose_name='Genre')),
                ('date_naissance', models.DateField(blank=True, null=True, verbose_name='Date de naissance')),
                ('date_recrutement', models.DateField(verbose_name='Date de recrutement')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Adresse Email')),
                ('est_actif', models.BooleanField(default=True, verbose_name='Agent en activité')),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=100, unique=True, verbose_name='Intitulé du poste')),
            ],
            options={
                'verbose_name': 'Poste',
                'verbose_name_plural': 'Postes',
            },
        ),
        migrations.CreateModel(
            name='Conge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_conge', models.CharField(choices=[('ANNUEL', 'Congé Annuel'), ('MALADIE', 'Congé Maladie'), ('MATERNITE', 'Maternité / Paternité'), ('SANS_SOLDE', 'Sans Solde')], default='ANNUEL', max_length=20, verbose_name='Type de congé')),
                ('date_debut', models.DateField(verbose_name='Date de début')),
                ('date_fin', models.DateField(verbose_name='Date de fin')),
                ('statut', models.CharField(choices=[('ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='ATTENTE', max_length=15, verbose_name='Statut')),
                ('duree_jours_stockee', models.IntegerField(default=0, editable=False, verbose_name='Nombre de jours')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conges', to='test_app.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Congé',
                'verbose_name_plural': 'Congés',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_entretien', models.DateField(verbose_name="Date de l'entretien")),
                ('annee_eval_nom', models.IntegerField(default=2026, verbose_name='Année évaluée')),
                ('competence_technique', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Compétences Techniques (/20)')),
                ('sens_du_service', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Sens du Service (/20)')),
                ('assiduite', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Assiduité (/20)')),
                ('objectif_atteint', models.DecimalField(decimal_places=2, default=10, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)], verbose_name='Objectifs Atteints (/20)')),
                ('commentaire_general', models.TextField(blank=True, verbose_name='Commentaires')),
                ('souhaits_evolution', models.TextField(blank=True, verbose_name="Souhaits d'évolution")),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='test_app.agent', verbose_name='Agent évalué')),
                ('evaluateur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_effectuees', to='test_app.agent', verbose_name='Supérieur Hiérarchique')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
            },
        ),
        migrations.CreateModel(
            name='GrilleIndiciaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50, verbose_name='Grade')),
                ('echelon', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Échelon')),
                ('indice_brut', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Indice Brut')),
                ('duree_minimum_mois', models.IntegerField(default=24, verbose_name='Durée minimale (mois) pour avancement')),
            ],
            options={
                'verbose_name': 'Grille Indiciaire',
                'verbose_name_plural': 'Grilles Indiciaires',
                'ordering': ['grade', 'echelon'],
                'unique_together': {('grade', 'echelon')},
            },
        ),
        migrations.CreateModel(
            name='EvolutionCarriere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_promotion', models.DateField(auto_now_add=True, verbose_name="Date de l'évolution")),
                ('motif', models.CharField(default="Avancement à l'ancienneté", max_length=255, verbose_name='Motif')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historique_carriere', to='test_app.agent', verbose_name='Agent')),
                ('ancien_grade_echelon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anciennes_evolutions', to='test_app.grilleindiciaire')),
                ('nouveau_grade_echelon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='nouvelles_evolutions', to='test_app.grilleindiciaire', verbose_name='Nouveau Grade/Échelon')),
            ],
            options={
                'verbose_name': 'Évolution de Carrière',
                'verbose_name_plural': 'Évolutions de Carrière',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='grille',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.grilleindiciaire', verbose_name='Situation Indiciaire (Grade/Échelon)'),
        ),
        migrations.AddField(
            model_name='agent',
            name='poste',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='test_app.poste', verbose_name='Poste / Fonction'),
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100, unique=True, verbose_name='Nom du service')),
                ('directeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dirige_service', to='test_app.agent', verbose_name='Directeur / Chef de service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.AddField(
            model_name='agent',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agents', to='test_app.service', verbose_name='Service affecté'),
        ),
        migrations.CreateModel(
            name='Paie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='Mois')),
                ('annee', models.IntegerField(verbose_name='Année')),
                ('salaire_base_historique', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Salaire de base (Figé)')),
                ('net_a_payer_stocke', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Net à Payer (Stocké)')),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Primes complémentaires')),
                ('indemnite_residence', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Indemnité de résidence')),
                ('SFT', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Supplément Familial de Traitement (SFT)')),
                ('retenues', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Autres retenues / Avances')),
                ('retenues_retraite', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Retenue Retraite')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bulletins_paie', to='test_app.agent', verbose_name='Agent')),
            ],
            options={
                'verbose_name': 'Bulletin de Paie',
                'verbose_name_plural': 'Bulletins de Paie',
                'unique_together': {('agent', 'mois', 'annee')},
            },
        ),
    ]
