"""
Django settings for systeme_GRHP project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u58id_r$m$o%a81pv)5p*wc@#s@+zlq3jgf-z70nxl)b^&)olg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Ton application
    'test_app',
]
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #'basicauth.middleware.BasicAuthMiddleware',  # 👈 À ajouter obligatoirement en premier
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # ... le reste de tes middlewares
]

ROOT_URLCONF = 'systeme_GRHP.urls'

# Configuration de la première barrière de sécurité (HTTP Basic Auth)
BASICAUTH_USERS = {
    "directeur_rh": "SgRhP_Bamako_@2026_SecureKey",  # Nom d'utilisateur et mot de passe système
}
BASE_DIR = Path(__file__).resolve().parent.parent
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Cette ligne doit être exactement comme ça
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request', # Requis pour Jazzmin/Admin
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
WSGI_APPLICATION = 'systeme_GRHP.wsgi.application'


#Tuile colore pour le thème Jazzmin
JAZZMIN_SETTINGS = {
    "site_title": "SGRHP Admin",
    "site_brand": "SGRHP",
    "welcome_sign": "Gestion SGRHP",
    "copyright": "SGRHP Ltd",
    "search_model": ["test_app.Agent", "auth.User"],
    "custom_css": "admin/css/custom_admin.css",
    "show_sidebar": True,
    "navigation_expanded": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    
    # Menu du haut unique et fonctionnel
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "permissions": ["auth.view_user"]},
        
    ],
    

    # Toutes tes icônes regroupées
    "icons": {
    "auth": "fas fa-users-cog",
    "auth.user": "fas fa-user",
    "auth.Group": "fas fa-users",
    "test_app.Agent": "fas fa-user-tie",
    "test_app.Service": "fas fa-building",
    "test_app.Poste": "fas fa-briefcase",
    "test_app.Conge": "fas fa-calendar-alt",
    "test_app.Paie": "fas fa-money-check-alt",
    "test_app.Evaluation": "fas fa-chart-line",
    },
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
}
#Personnalisation de l'interface d'administration
JAZZMIN_UI_CUSTOMIZER_CONFIG = {
    "navbar_fixed": True,
    "sidebar_fixed": True,
    "sidebar": "sidebar-dark-primary",
    "brand_colour": "navbar-primary",
    "navbar": "navbar-dark",
    "accent": "accent-primary",
    "sidebar_nav_child_indent": True,
    "button_classes": {
    "primary": "btn-primary",
    "secondary": "btn-secondary",
    "info": "btn-info",
    "warning": "btn-warning",
    "danger": "btn-danger",
    "success": "btn-success"
    }
}


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'systeme_GRHP',
        'USER': '',
        'PASSWORD': '',
        'HOST': 'localhost\\SQLEXPRESS',
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Trusted_Connection=yes;TrustServerCertificate=yes;',
        },
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
