"""
Django settings for systeme_GRHP project.

Generated by 'django-admin startproject' using Django 6.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
import mimetypes
mimetypes.add_type("text/javascript", ".js", True)
mimetypes.add_type("text/css", ".css", True)


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u58id_r$m$o%a81pv)5p*wc@#s@+zlq3jgf-z70nxl)b^&)olg'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

AUTH_USER_MODEL = 'agents.Utilisateur'

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'django_filters',
    
    'agents',
    
]
MIDDLEWARE = [
    #'basicauth.middleware.BasicAuthMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # ... le reste de tes middlewares
]

ROOT_URLCONF = 'systeme_GRHP.urls'

# Configuration de la première barrière de sécurité (HTTP Basic Auth)
BASICAUTH_USERS = {
    "directeur_rh": "SgRhP_Bamako_@2026_SecureKey",  # Nom d'utilisateur et mot de passe système
}
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',  # 👈 Crucial pour Jazzmin et l'UI Builder
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'systeme_GRHP.wsgi.application'

# ==============================================================================
# CONFIGURATION JAZZMIN OPTIMISÉE POUR LE SGRHP
# ==============================================================================
JAZZMIN_SETTINGS = {
    # === Titres et Identité Visuelle ===
    "site_title": "SGRHP Administration",
    "site_header": "SGRHP",
    "site_brand": "SGRHP Mali",
    "site_logo": None,  # Change par le chemin de ton logo si nécessaire (ex: "img/logo.png")

    # === Menu de navigation & Ergonomie ===
    "show_sidebar": True,
    "navigation_expanded": True,
    
    # Masquer les applications techniques de Django qui n'intéressent pas les RH
    "hide_apps": ["contenttypes", "sessions"],
    "hide_models": ["admin.logentry"],
    
    # Ordre des applications dans le menu latéral
    "order_with_respect_to": ["auth", "agents", "payroll", "conges", "dashboard"],
    
    # Liens personnalisés globaux dans le menu latéral
    "side_menu_links": [
        {"name": "Accueil", "url": "admin:index", "icon": "fas fa-home"},
        {"name": "Tableau de bord", "url": "admin:dashboard", "icon": "fas fa-tachometer-alt"},
        {"name": "Documentation", "url": "https://docs.djangoproject.com/en/6.0/", "icon": "fas fa-book"},
    ],

    # === Liens du Menu Supérieur (Top Menu) ===
    "topmenu_links": [
        {"name": "Accueil", "url": "admin:index", "icon": "fas fa-home"},
    ],

    # === Personnalisation des Icônes (FontAwesome) ===
    "default_icon": "fas fa-chevron-right",
    "default_icon_parents": "fas fa-folder",
    "default_icon_children": "fas fa-file",
    
    "icons": {
        # Applications
        "auth": "fas fa-shield-alt",
        "agents": "fas fa-id-badge",
        "payroll": "fas fa-credit-card",
        "conges": "fas fa-calendar-check",
        "dashboard": "fas fa-tachometer-alt",
        
        # Modèles spécifiques (nom de l'app.nom_du_modele en minuscules)
        "auth.user": "fas fa-user-circle",
        "auth.group": "fas fa-users",
        "agents.agent": "fas fa-user",
        "payroll.salaire": "fas fa-money-bill-wave",
        "conges.conge": "fas fa-calendar-alt",
    },
    
    # === Interface & Formulaires ===
    "changeform_format": "horizontal_tabs",  # Organisation propre des formulaires longs
    "related_modal_active": True,            # Ouverture des relations dans des fenêtres modales

    # === Thème Visuel ===
    "theme": "flatly",
    "dark_mode_theme": None,                 # Évite de forcer le mode sombre au rendu
    "show_ui_builder": False,                # Désactivé en production (à passer à True si tu veux modifier le design en live)
    
    # Fichier CSS personnalisé
    "custom_css": "css/style.css",
}
# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases


load_dotenv() # Charge les variables du fichier .env

DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': os.getenv('DB_NAME'),  # Récupère "systeme_GRHP" depuis le .env
        'USER': os.getenv('DB_USER'),
        'PASSWORD': '',
        'HOST': os.getenv('DB_HOST'),  # Récupère "localhost\SQLEXPRESS" depuis le .env
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 18 for SQL Server',
            'extra_params': 'Trusted_Connection=yes;TrustServerCertificate=yes;',
        },
    }
}
# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

BASE_DIR = Path(__file__).resolve().parent.parent

# L'URL pour accéder aux fichiers dans le navigateur
STATIC_URL = 'static/'

# 1. Où Django COLLECTE les fichiers pour la production (votre dossier à la racine)
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# 2. Où Django CHERCHE vos fichiers sources en développement
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'), 
]